/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HabitTracker {
    }
}
declare global {
    interface HTMLHabitTrackerElement extends Components.HabitTracker, HTMLStencilElement {
    }
    var HTMLHabitTrackerElement: {
        prototype: HTMLHabitTrackerElement;
        new (): HTMLHabitTrackerElement;
    };
    interface HTMLElementTagNameMap {
        "habit-tracker": HTMLHabitTrackerElement;
    }
}
declare namespace LocalJSX {
    interface HabitTracker {
    }
    interface IntrinsicElements {
        "habit-tracker": HabitTracker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "habit-tracker": LocalJSX.IntrinsicElements["habit-tracker"] & JSXBase.HTMLAttributes<HTMLHabitTrackerElement>;
        }
    }
}
